name: Debug

on:
  push:
    branches: [main]
    paths: ['.github/workflows/debug.yml']
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-14
    permissions:
      contents: write
    steps:
      - name: A
        run: echo "step A ok"
